Repository pravega/pravega, pull requests merged in 2018-02, with the labels that each got.

#2302 Issue 2034: Enable TLS for segmentstore to bookkeeper interactions
  config/bookie.keystore.jks
  config/bookie.keystore.jks.passwd
  config/bookie.truststore.jks
  config/client.truststore.jks
  docker/bookkeeper/entrypoint.sh
  gradle/rat.gradle
  segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfig.java
  segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java
  segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java
  segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java
Labels: area/security, area/tier1, kind/feature

#2318 Issue 2317 : BookKeeperServiceRunner should honor `secureBk` settings
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/BookKeeperRunner.java
  segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java
Labels: kind/bug

#2301 Issue 2222: Compact reader group state.
  client/src/main/java/io/pravega/client/state/StateSynchronizer.java
  client/src/main/java/io/pravega/client/state/impl/StateSynchronizerImpl.java
  client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
  client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
  client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
  client/src/test/java/io/pravega/client/state/impl/SynchronizerTest.java
  client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
  client/src/test/java/io/pravega/client/stream/impl/StreamSegmentsTest.java
Labels: area/client, kind/enhancement
