Repository pravega/pravega, pull requests merged in 2019-10, with the labels that each got.

#4232 Issue 4231: Use system truststore for TLS when client truststore is not specified
  client/src/main/java/io/pravega/client/netty/impl/ConnectionPoolImpl.java
  client/src/test/java/io/pravega/client/netty/impl/ConnectionPoolImplTest.java
Labels: version/0.6.0

#4253 Issue 4252: Change connection pooling to default to off on append path.
  client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
Labels: area/performance, kind/enhancement

#4257 Issue 4256: bring back the ignored test with openJDK 8
  shared/metrics/src/test/java/io/pravega/shared/MetricsTagsTest.java
Labels: area/testing, kind/bug, priority/P0, version/0.6.0
