Repository pravega/pravega, pull requests merged in 2019-12, with the labels that each got.

#4410 Issue 4409: Reset tokenRefreshFuture upon exception in obtaining a new delegation token
  client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java
  client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
  client/src/test/java/io/pravega/client/security/auth/JwtTokenProviderImplTest.java
Labels: version/0.6.0, version/0.7.0

#4370 Issue 3679: Increase maximum event size limit.
  client/src/main/java/io/pravega/client/stream/Serializer.java
  shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
  test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
  test/system/src/test/java/io/pravega/test/system/LargeEventTest.java
Labels: area/performance, kind/enhancement, kind/feature, priority/P3, version/0.7.0

#4427 Issue 3503: Disable HDFSIntegrationTest.
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/HDFSIntegrationTest.java
Labels: area/tier2, kind/bug
