Repository pravega/pravega, pull requests merged in 2019-09, with the labels that each got.

#4081 Issue 3344: Reader side of watermarking implementation
  client/src/main/java/io/pravega/client/segment/impl/NoSuchSegmentException.java
  client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamFactoryImpl.java
  client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java
  client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java
  client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamFactoryImpl.java
  client/src/main/java/io/pravega/client/state/SynchronizerConfig.java
  client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java
  client/src/main/java/io/pravega/client/stream/EventStreamReader.java
  client/src/main/java/io/pravega/client/stream/ReaderConfig.java
  client/src/main/java/io/pravega/client/stream/TimeWindow.java
  client/src/main/java/io/pravega/client/stream/impl/ClientFactoryImpl.java
  client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java
  client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java
  client/src/main/java/io/pravega/client/stream/impl/PositionImpl.java
  client/src/main/java/io/pravega/client/stream/impl/PositionInternal.java
  client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java
  client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java
  client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java
  client/src/main/java/io/pravega/client/stream/impl/SegmentWithRange.java
  client/src/main/java/io/pravega/client/stream/impl/WatermarkReaderImpl.java
  client/src/main/java/io/pravega/client/stream/impl/WriterPosition.java
  client/src/test/java/io/pravega/client/admin/impl/StreamManagerImplTest.java
  client/src/test/java/io/pravega/client/state/impl/RevisionedStreamClientTest.java
  client/src/test/java/io/pravega/client/state/impl/SynchronizerTest.java
  client/src/test/java/io/pravega/client/stream/impl/EventStreamReaderTest.java
  client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
  client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateTest.java
  client/src/test/java/io/pravega/client/stream/impl/SerializationTest.java
  client/src/test/java/io/pravega/client/stream/impl/WatermarkReaderImplTest.java
  client/src/test/java/io/pravega/client/stream/mock/MockClientFactory.java
  client/src/test/java/io/pravega/client/stream/mock/MockController.java
  common/src/main/java/io/pravega/common/concurrent/LatestItemSequentialProcessor.java
  common/src/test/java/io/pravega/common/concurrent/LatestItemSequentialProcessorTest.java
  controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java
  controller/src/main/java/io/pravega/controller/server/bucket/PeriodicWatermarking.java
  controller/src/main/java/io/pravega/controller/server/rest/generated/model/CreateScopeRequest.java
  controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
  controller/src/test/java/io/pravega/controller/mocks/EventStreamReaderMock.java
  shared/protocol/src/main/java/io/pravega/shared/segment/StreamSegmentNameUtils.java
  shared/protocol/src/main/java/io/pravega/shared/watermarks/SegmentWithRange.java
  shared/protocol/src/main/java/io/pravega/shared/watermarks/Watermark.java
  standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java
  test/integration/src/test/java/io/pravega/test/integration/BoundedStreamReaderTest.java
  test/integration/src/test/java/io/pravega/test/integration/ControllerWatermarkingTest.java
  test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java
  test/integration/src/test/java/io/pravega/test/integration/StreamSeekTest.java
  test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java
  test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndReaderGroupTest.java
  test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndTruncationTest.java
Labels: version/0.6.0

#4131 Issue 4129: Ensure that a failure to connect propagates upward
  client/src/main/java/io/pravega/client/netty/impl/ConnectionPoolImpl.java
  client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java
  client/src/test/java/io/pravega/client/netty/impl/FlowHandlerTest.java
Labels: area/client, area/testing, kind/bug

#4188 Issue 3344: Update offset order before acking.
  client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
Labels: kind/enhancement, priority/P3

#4190 Issue 4189: Add timeouts to integration tests
  test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
  test/integration/src/test/java/io/pravega/test/integration/ReadTest.java
  test/integration/src/test/java/io/pravega/test/integration/ReaderGroupTest.java
  test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
  test/integration/src/test/java/io/pravega/test/integration/TransactionTest.java
  test/integration/src/test/java/io/pravega/test/integration/controller/server/DebugStreamSegmentsTest.java
  test/integration/src/test/java/io/pravega/test/integration/endtoendtest/AbstractEndToEndTest.java
Labels: area/testing

#4185 Issue 4184: Update security configuration documentation
  documentation/src/docs/security/pravega-security-configurations.md
Labels: version/0.6.0

#4183 Issue 3268: Standalone mode security documentation
  documentation/src/docs/deployment/run-local.md
  documentation/src/docs/security/securing-standalone-mode-cluster.md
Labels: version/0.6.0

#4212 Issue 4211: Fix backward compatibility bug allowing unread fields
  shared/protocol/src/main/java/io/pravega/shared/protocol/netty/CommandDecoder.java
  shared/protocol/src/main/java/io/pravega/shared/protocol/netty/CommandEncoder.java
  shared/protocol/src/test/java/io/pravega/shared/protocol/netty/CommandDecoderTest.java
Labels: version/0.6.0

#4220 Issue 4217: Support automatically noting time
  client/src/main/java/io/pravega/client/stream/EventStreamWriter.java
  client/src/main/java/io/pravega/client/stream/TimeWindow.java
  client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
  client/src/main/java/io/pravega/client/stream/impl/WriterPosition.java
  client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
  test/testcommon/src/main/java/io/pravega/test/common/CollectingExecutor.java
Labels: area/client, kind/feature, priority/P2, version/0.6.0
