Repository pravega/pravega, pull requests merged in 2020-12, with the labels that each got.

#5380 Issue 5379: Allow retrieving delegation tokens with write access for watermark streams
  controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
  controller/src/test/java/io/pravega/controller/server/rpc/grpc/v1/InMemoryControllerServiceImplTest.java
Labels: area/controller, area/security, version/0.9.0

#5398 Issue 5382: Adding Java cacerts to openjdk:11.0.8-jre-slim Base Image
  docker/pravega/Dockerfile
  docker/pravega/scripts/common.sh
Labels: version/0.9.0

#5366 Issue 5360: Require permissions on the scope for creating Key-Value Tables
  controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java
  shared/security/src/main/java/io/pravega/shared/security/auth/AuthorizationResource.java
  shared/security/src/main/java/io/pravega/shared/security/auth/AuthorizationResourceImpl.java
  shared/security/src/test/java/io/pravega/shared/security/auth/AuthorizationResourceImplTest.java
Labels: version/0.9.0

#5363 Issue 4902: (SLTS) - Implement more efficient eviction cache for ReadIndexCache
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ReadIndexCache.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ReadIndexCacheTests.java
Labels: area/tier2

#5346 Issue 5330: SLTS - Handle partially written chunks and snapshots after failures.
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/CleanupHelper.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
Labels: area/tier2

#5413 Issue 4903: More robust garbage collection
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/DefragmentOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/ChunkMetadata.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/SegmentMetadata.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/StatusFlags.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollectorTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/StorageMetadataSerializationTests.java
Labels: area/lts

#5436 Issue 5435: Allow DefaultCredentials to be assigned to both new and legacy Credentials interface
  client/src/main/java/io/pravega/client/stream/impl/DefaultCredentials.java
  client/src/test/java/io/pravega/client/CredentialsExtractorTest.java
Labels: version/0.9.0
