Repository pravega/pravega, pull requests merged in 2021-11, with the labels that each got.

#6417 Issue 6391: LTS - Enable STS temp tokens with S3 Binding.
  bindings/src/main/java/io/pravega/storage/s3/S3SimpleStorageFactory.java
  bindings/src/main/java/io/pravega/storage/s3/S3StorageConfig.java
  bindings/src/test/java/io/pravega/storage/StorageFactoryTests.java
  bindings/src/test/java/io/pravega/storage/s3/S3SimpleStorageTests.java
  bindings/src/test/java/io/pravega/storage/s3/S3StorageConfigTest.java
  bindings/src/test/java/io/pravega/storage/s3/S3TestContext.java
Labels: area/lts

#6209 Issue 5886: SLTS - Fix several flaky tests. Use multiple threads in tests to uncover more thread/timing related issues.
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SimpleStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
Labels: area/lts

#6421 Issue 4912 : LTS - Efficient space reclamation after truncation by relocating first chunk.
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorageMetrics.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
Labels: area/lts, version/0.11.0

#6426 Issue 6389: LTS - Report percentage used space.
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
  shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
Labels: area/lts, version/0.11.0

#6418 Issue 6371: CLI commands that help inspect values in Controller Metadata Tables
  cli/admin/README.md
  cli/admin/src/main/java/io/pravega/cli/admin/AdminCommand.java
  cli/admin/src/main/java/io/pravega/cli/admin/controller/ControllerCommand.java
  cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataCommand.java
  cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataGetEntryCommand.java
  cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataListEntriesCommand.java
  cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataListKeysCommand.java
  cli/admin/src/main/java/io/pravega/cli/admin/controller/metadata/ControllerMetadataTablesInfoCommand.java
  cli/admin/src/main/java/io/pravega/cli/admin/serializers/controller/ControllerKeySerializer.java
  cli/admin/src/main/java/io/pravega/cli/admin/serializers/controller/ControllerMetadataSerializer.java
  cli/admin/src/test/java/io/pravega/cli/admin/controller/AbstractControllerMetadataCommandsTest.java
  cli/admin/src/test/java/io/pravega/cli/admin/serializers/controller/ControllerKeySerializerTest.java
  cli/admin/src/test/java/io/pravega/cli/admin/serializers/controller/ControllerMetadataSerializerTest.java
  cli/admin/src/test/java/io/pravega/cli/admin/utils/TestUtils.java
  client/src/main/java/io/pravega/client/stream/RetentionPolicy.java
  client/src/main/java/io/pravega/client/stream/StreamConfiguration.java
  controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java
  controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStream.java
  controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java
  controller/src/main/java/io/pravega/controller/store/stream/records/ActiveTxnRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/CommittingTransactionsRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/CompletedTxnRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/EpochTransitionRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/HistoryTimeSeries.java
  controller/src/main/java/io/pravega/controller/store/stream/records/HistoryTimeSeriesRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/RetentionSet.java
  controller/src/main/java/io/pravega/controller/store/stream/records/SealedSegmentsMapShard.java
  controller/src/main/java/io/pravega/controller/store/stream/records/StateRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/StreamConfigurationRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/StreamCutRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/StreamCutReferenceRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/StreamSegmentRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/StreamSubscriber.java
  controller/src/main/java/io/pravega/controller/store/stream/records/StreamTruncationRecord.java
  controller/src/main/java/io/pravega/controller/store/stream/records/Subscribers.java
  controller/src/main/java/io/pravega/controller/store/stream/records/WriterMark.java
  controller/src/test/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStoreTest.java
  controller/src/test/java/io/pravega/controller/store/stream/records/ControllerMetadataRecordToStringTest.java
  shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
Labels: area/controller, area/cli

#6438 Issue 6437: Fix flaky test EventProcessorGroupTest.testFailingCellShutdown
  controller/src/test/java/io/pravega/controller/eventprocessor/EventProcessorGroupTest.java
Labels: area/controller, tag/flakeyTest
