Repository pravega/pravega, pull requests merged in 2021-03, with the labels that each got.

#5800 Issue 5798: (SLTS) Fix close in GarbageCollector, ExtendedS3ChunkStorage and HDFSChunkStorage.
  bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3ChunkStorage.java
  bindings/src/main/java/io/pravega/storage/hdfs/HDFSChunkStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStore.java
Labels: area/lts, version/0.9.1

#5815 Issue 5814: (r.0.9) Change pravegaVersion to 0.9.1-SNAPSHOT.
  gradle.properties
Labels: kind/release

#5790 Issue 5788: (SLTS) Remove ACL operations from ExtendedS3ChunkStorage
  bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3ChunkStorage.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorageTests.java
Labels: version/0.9.1

#5811 Issue 5810: (SegmentStore) Fixed a StorageWriter bug that could lead to data loss
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/WriterState.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/WriterStateTests.java
Labels: version/0.9.1

#5809 Issue 5808: SLTS - Fix Preconditions checks to include enough information in message.
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ReadIndexCache.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ReadOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/MetadataTransaction.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/SegmentMetadata.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/NoAppendSimpleStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ReadIndexCacheTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/SegmentMetadataTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/StorageMetadataSerializationTests.java
Labels: version/0.9.1

#5836 Issue 5628: Speed up WatermarkingTest
  test/integration/src/test/java/io/pravega/test/integration/PravegaResource.java
  test/integration/src/test/java/io/pravega/test/integration/WatermarkingTest.java
Labels: tag/tech-debt

#5804 Issue 5789: (SegmentStore) Improving stability during Segment Container Recoveries
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheUtilizationProvider.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/ReadIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/MemoryStateUpdater.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/Throttler.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentMetadataComparer.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DurableLogTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/MemoryStateUpdaterTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationLogTestBase.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerCalculatorTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
  segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/ThrottlerSourceListenerCollection.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/ThrottlerSourceListenerCollectionTests.java
Labels: version/0.9.1

#5586 Issue 5581: (SegmentStore) Disabling non-essential cache inserts if cache utilization is high
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/CachePolicy.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ReadIndexSummary.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyCache.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentKeyCache.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/CacheManagerTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/AttributeIndexTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyCacheTests.java
Labels: version/0.9.1

#5854 Issue 5726: Ensure the Pravega standalone is up and running before attempting to run tests.
  standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java
  standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java
  standalone/src/test/java/io/pravega/local/PravegaEmulatorResource.java
  standalone/src/test/java/io/pravega/local/SecurePravegaClusterTest.java
  standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java
  standalone/src/test/resources/logback-test.xml
Labels: tag/tech-debt

#5841 Issue 5840: (SegmentStore) Fixed a deadlock in SegmentKeyCache.
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentKeyCache.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/AsyncTableEntryReaderTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyCacheTests.java
Labels: version/0.9.1

#5858 Issue 5853: SLTS - BaseMetadataStore.get does not return deep copy when loading from store.
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/MockStorageMetadata.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStoreMockTests.java
Labels: area/lts

#5867 Issue 5866: (SLTS) ReadIndexCache stats not reported.
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
Labels: area/lts

#5860 Issue 5859: (v0.9.1) Cherry-pick various SegmentStore bug fixes
  common/src/main/java/io/pravega/common/util/AbstractBufferView.java
  common/src/main/java/io/pravega/common/util/BufferView.java
  common/src/main/java/io/pravega/common/util/ByteArraySegment.java
  common/src/main/java/io/pravega/common/util/CompositeBufferView.java
  common/src/main/java/io/pravega/common/util/CompositeByteArraySegment.java
  common/src/test/java/io/pravega/common/util/AbstractBufferViewTests.java
  common/src/test/java/io/pravega/common/util/BufferViewTestBase.java
  common/src/test/java/io/pravega/common/util/CompositeBufferViewTests.java
  segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/ReadResult.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/CachePolicy.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheUtilizationProvider.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/ReadIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/WriterFlushResult.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeBTreeIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLog.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/MemoryStateUpdater.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/SegmentMetadataUpdateTransaction.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/Throttler.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/AsyncReadResultHandler.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/AsyncReadResultProcessor.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ReadIndexSummary.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadResult.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/AsyncTableEntryReader.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyCache.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentKeyCache.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/WriterTableProcessor.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/WriterState.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/CacheManagerTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentMetadataComparer.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/AttributeIndexTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DurableLogTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/MemoryStateUpdaterTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/OperationLogTestBase.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/ThrottlerCalculatorTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/StreamSegmentReadResultTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/AsyncTableEntryReaderTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyCacheTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ReadResultMock.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/WriterTableProcessorTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/WriterStateTests.java
  segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/ThrottlerSourceListenerCollection.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/ThrottlerSourceListenerCollectionTests.java
  shared/protocol/src/main/java/io/pravega/shared/protocol/netty/ByteBufWrapper.java
  shared/protocol/src/test/java/io/pravega/shared/protocol/netty/ByteBufWrapperTests.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/TruncateableArray.java
Labels: version/0.9.1

#5819 Issue 5818: Cherry-pick PR 5735 into r0.9
  client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
  client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
Labels: version/0.9.1

#5826 Issue 5824: Cherry pick fix for issue 5693 to r0.9
  client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java
  client/src/main/java/io/pravega/client/control/impl/ControllerImpl.java
  client/src/main/java/io/pravega/client/control/impl/ModelHelper.java
  client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java
  client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java
  client/src/main/java/io/pravega/client/stream/impl/ReaderGroupNotFoundException.java
  client/src/test/java/io/pravega/client/admin/impl/ReaderGroupManagerImplTest.java
  client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java
  client/src/test/java/io/pravega/client/stream/impl/ReaderGroupImplTest.java
  client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java
  client/src/test/java/io/pravega/client/stream/mock/MockController.java
  client/src/test/java/io/pravega/client/stream/mock/MockStreamManager.java
  controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java
  controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/CreateReaderGroupTask.java
  controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java
  controller/src/test/java/io/pravega/controller/server/ControllerServiceWithStreamTest.java
  controller/src/test/java/io/pravega/controller/server/eventProcessor/LocalControllerTest.java
  controller/src/test/java/io/pravega/controller/server/rpc/auth/ControllerGrpcAuthFocusedTest.java
  controller/src/test/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImplTest.java
  controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java
  controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java
  test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java
  test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java
  test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndReaderGroupTest.java
Labels: version/0.9.1

#5822 Issue 5823: Cherrypick fix for 5393 to r0.9
  client/src/main/java/io/pravega/client/connection/impl/FlowHandler.java
  controller/src/conf/logback.xml
  controller/src/main/java/io/pravega/controller/server/SegmentHelper.java
  dist/conf/logback.xml
Labels: version/0.9.1

#5252 Issue 5162: (SegmentStore) Table Segment Throttling and bug fixes
  client/src/main/java/io/pravega/client/tables/impl/TableSegmentImpl.java
  client/src/test/java/io/pravega/client/stream/mock/MockStreamManager.java
  client/src/test/java/io/pravega/client/tables/impl/TableSegmentImplTest.java
  common/src/main/java/io/pravega/common/concurrent/AsyncSemaphore.java
  common/src/test/java/io/pravega/common/concurrent/AsyncSemaphoreTests.java
  segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java
  segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/ConnectionTracker.java
  segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaConnectionListener.java
  segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
  segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/TrackedConnection.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorAuthFailedTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/ConnectionTrackerTests.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorAuthFailedTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/EntrySerializer.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/KeyUpdateCollection.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentSortedKeyIndexImpl.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableExtensionConfig.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableKeyBatch.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableWriterConnector.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/WriterTableProcessor.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImplTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/KeyUpdateCollectionTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableCompactorTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableContext.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableEntryDeltaIteratorTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/WriterTableProcessorTests.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/Reporter.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/SelfTest.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/SelfTestRunner.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/TableConsumer.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/TableProducerDataSource.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/TableUpdate.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/TestConfig.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/AppendProcessorAdapter.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/ClientAdapterBase.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/ExternalAdapter.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/InProcessListenerWithRealStoreAdapter.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/InProcessMockClientAdapter.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/SegmentStoreAdapter.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/StoreAdapter.java
  test/integration/src/test/java/io/pravega/test/integration/AppendTest.java
Labels: version/0.10.0

#4965 Issue 4964: Prevent a busy loop while waiting for the segments to be updated
  client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
  client/src/test/java/io/pravega/client/stream/impl/EventStreamWriterTest.java
Labels: area/client, kind/enhancement

#5862 Issue 5861: (SLTS) Make metadata buffer size and metadata cache size configurable.
  bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3SimpleStorageFactory.java
  bindings/src/main/java/io/pravega/storage/filesystem/FileSystemSimpleStorageFactory.java
  bindings/src/main/java/io/pravega/storage/hdfs/HDFSSimpleStorageFactory.java
  bindings/src/test/java/io/pravega/storage/StorageFactoryTests.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ExtendedS3IntegrationTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/NonAppendExtendedS3IntegrationTest.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/SimpleStorageFactory.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemorySimpleStorageFactory.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryStorageFactoryCreator.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedRollingStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollectorTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SimpleStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStoreMockTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStoreTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemorySimpleStorageFactoryTests.java
Labels: area/lts
