Repository pravega/pravega, pull requests merged in 2021-08, with the labels that each got.

#6108 Issues 6086: SLTS - Robust garbage collection (PDP-53).
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ExtendedS3IntegrationTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/FileSystemIntegrationTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/HDFSIntegrationTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/NonAppendExtendedS3IntegrationTest.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StorageEventProcessor.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StorageEventProcessorTests.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AbstractTaskQueueManager.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkIterator.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorageMetrics.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/DefragmentOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/MetadataTransaction.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/StorageTestBase.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedRollingStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollectorTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SimpleStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/TestUtils.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemoryTaskQueueManager.java
  shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
Labels: area/lts, version/0.10.0

#6185 Issue 6184: SLTS - Fix generation of inconsistent snapshots
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
  shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
Labels: area/lts

#6199 Cherry-pick 6184: SLTS - Fix generation of inconsistent snapshots (#6185)
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
  shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
Labels: area/lts, version/0.9.2

#6207 Issue 6205: ListKeyValueTables API throws NullPointerException if metadataTable storing list of KVTs in Scope is deleted.
  client/src/main/java/io/pravega/client/connection/impl/ConnectionPoolImpl.java
  controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java
  controller/src/main/java/io/pravega/controller/store/kvtable/PravegaTablesKVTMetadataStore.java
  controller/src/test/java/io/pravega/controller/server/eventProcessor/PravegaTablesScaleRequestHandlerTest.java
  controller/src/test/java/io/pravega/controller/store/kvtable/PravegaTablesKVTMetadataStoreTest.java
  controller/src/test/java/io/pravega/controller/store/stream/TestStreamStoreFactory.java
Labels: kind/bug, area/controller

#6224 Issue 6223: SLTS - GC deleteSegment delete/update metadata in small batches.
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollectorTests.java
Labels: area/lts, version/0.10.0

#6227 Issue 6226: Update of security documentation.
  documentation/src/docs/security/pravega-security-configurations.md
  documentation/src/docs/security/securing-distributed-mode-cluster.md
  documentation/src/docs/security/securing-standalone-mode-cluster.md
Labels: area/security, area/documentation
