Repository pravega/pravega, pull requests merged in 2021-04, with the labels that each got.

#5903 Issue 5902: SLTS - Metrics Improvements and minor perf improvements
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorageMetrics.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ReadOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
  shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
Labels: area/lts

#5908 Issue 5907: (SegmentStore) Enabling rollover and compaction for container metadata table segment.
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/TableMetadataStore.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtension.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableExtensionConfig.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/TableMetadataStoreTests.java
Labels: version/0.10.0, version/0.9.1

#5920 Issue 5919: Cherry-pick #5908 into r0.9
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/TableMetadataStore.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/TableMetadataStoreTests.java
Labels: version/0.9.1

#5924 Issue 5923: cherry pick to r0.9
  bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3SimpleStorageFactory.java
  bindings/src/main/java/io/pravega/storage/filesystem/FileSystemSimpleStorageFactory.java
  bindings/src/main/java/io/pravega/storage/hdfs/HDFSSimpleStorageFactory.java
  bindings/src/test/java/io/pravega/storage/StorageFactoryTests.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ExtendedS3IntegrationTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/NonAppendExtendedS3IntegrationTest.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/SimpleStorageFactory.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorageMetrics.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ReadOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemorySimpleStorageFactory.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/InMemoryStorageFactoryCreator.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedRollingStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageMockTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollectorTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SimpleStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStoreMockTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/TableBasedMetadataStoreTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemorySimpleStorageFactoryTests.java
  shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java
Labels: version/0.9.1

#5904 Issue 5698: SLTS - SystemJournal should create new snapshots periodically
  segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/Attributes.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ExtendedS3IntegrationTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/FileSystemIntegrationTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/HDFSIntegrationTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/NonAppendExtendedS3IntegrationTest.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerConfig.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SnapshotInfo.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SnapshotInfoStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/MetadataTransaction.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemorySnapshotInfoStore.java
  shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
  shared/protocol/src/test/java/io/pravega/shared/NameUtilsTest.java
Labels: version/0.9.1

#5962 Issue 5961: Cherry pick 5904 into 0.9 #5961
  segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/Attributes.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/ExtendedS3IntegrationTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/FileSystemIntegrationTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/HDFSIntegrationTest.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/NonAppendExtendedS3IntegrationTest.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerConfig.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SnapshotInfo.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SnapshotInfoStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/MetadataTransaction.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/metadata/ChunkMetadataStoreTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemorySnapshotInfoStore.java
  shared/protocol/src/main/java/io/pravega/shared/NameUtils.java
  shared/protocol/src/test/java/io/pravega/shared/NameUtilsTest.java
Labels: area/lts, version/0.9.1

#5945 Issue 5934: (KVT Beta 2) Retired Sorted Table Segments
  cli/user/src/test/java/io/pravega/cli/user/kvs/KVTCommandsTest.java
  common_server/src/main/java/io/pravega/common/util/btree/SearchResult.java
  common_server/src/main/java/io/pravega/common/util/btree/sets/BTreeSet.java
  common_server/src/main/java/io/pravega/common/util/btree/sets/BTreeSetPage.java
  common_server/src/main/java/io/pravega/common/util/btree/sets/ItemIterator.java
  common_server/src/main/java/io/pravega/common/util/btree/sets/PageCollection.java
  common_server/src/main/java/io/pravega/common/util/btree/sets/PagePointer.java
  common_server/src/main/java/io/pravega/common/util/btree/sets/TreeModificationContext.java
  common_server/src/main/java/io/pravega/common/util/btree/sets/UpdateItem.java
  common_server/src/test/java/io/pravega/common/util/btree/sets/BTreeSetPageTests.java
  common_server/src/test/java/io/pravega/common/util/btree/sets/BTreeSetTests.java
  segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/SegmentType.java
  segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/tables/TableAttributes.java
  segmentstore/contracts/src/test/java/io/pravega/segmentstore/contracts/SegmentTypeTests.java
  segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
  segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerSortedKeyIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImpl.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/KeyTranslator.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentSortedKeyIndex.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SegmentSortedKeyIndexImpl.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/SortedKeyIndexDataSource.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableKeyBatch.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/TableWriterConnector.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/WriterTableProcessor.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/TableStoreMock.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/MetadataStoreTestBase.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentMetadataTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/PriorityCalculatorTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerKeyIndexTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerSortedKeyIndexTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/ContainerTableExtensionImplTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/KeyTranslatorTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableCompactorTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableEntryDeltaIteratorTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/TableServiceTests.java
  segmentstore/server/src/test/java/io/pravega/segmentstore/server/tables/WriterTableProcessorTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/InMemoryTableStore.java
  shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/TestConfig.java
  test/integration/src/main/java/io/pravega/test/integration/selftest/adapters/SegmentStoreAdapter.java
  test/integration/src/test/java/io/pravega/test/integration/KeyValueTableTest.java
Labels: area/tables, version/0.10.0

#5964 Issue 5963: SLTS - writeSnapshotInfo should not block in case of cache throttle.
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/TableMetadataStore.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/AttributeAggregator.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ReadOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
Labels: area/lts

#5979 SLTS - Cherry-pick #5964 into r0.9 branch
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/TableMetadataStore.java
  segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/AttributeAggregator.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ReadOperation.java
  segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalOperationsTests.java
  segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java
Labels: area/lts, version/0.9.1
